### ISSUE TITLE
npm ERR! notarget No matching version found for @choerodon/boot@0.18.2

### ISSUE THREAD

**Issue by udhayamgit** [choerodon/choerodon-front#2]
/choerodon/choerodon-front$ npm install
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @choerodon/boot@0.18.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'choerodon-front'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devops/.npm/_logs/2019-07-12T12_23_54_130Z-debug.log

**Comment by HuangQiii** [comment]
you can use @choerodon/boot@0.18.1

that's may be our negligence, because of we have private npm source, and we test our latest code there, you can edit the package.json like below:

```json
"dependencies": {
    "@choerodon/boot": "0.18.x",
    "@choerodon/master": "0.18.x",
  }
```

or specific version like `0.18.1`
