### ISSUE TITLE
Not able to access choerodon 

### ISSUE THREAD

**Issue by udhayamgit** [choerodon/choerodon-front#3]
I'm not able to run npm install instead i did yarn install and yarn start. After Build sucessfully How to access the choerodon front? 

I'm not able to find the One click setup in the documentation.

📦  building modules (10990/10991 modules)DEPRECATION WARNING on line 24 of /home/devops/choerodon/choerodon-front/node_modules/@choerodon/boot/lib/containers/components/c7n/header/style/Logo.scss:
The operation `#3F51B5 minus #0f1216` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
http://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions

📦  building modules (10994/10994 modules)Extracted theme color css content length: 27553

webpack: bundle build is now finished.

 DONE  Compiled successfully in 202191ms                                                                                            12:58:36 PM

**Comment by HuangQiii** [comment]
what version of choerodon-front-boot?

there's no reason yarn can but npm can not. i am confused.

if you run npm start, it will open brower on 8080 automaticly

can you provide more infomations, it strange🧐
