### ISSUE TITLE
npm install ERR: core-js

### ISSUE THREAD

**Issue by xailocker** [choerodon/choerodon-front#4]
npm WARN **deprecated core-js@1.2.7**: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @choerodon/boot@0.18.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'choerodon-front'
npm ERR! notarget

**Comment by HuangQiii** [comment]
@xailocker fix the version of @choerodon/boot in package.json to 0.18.1 or 0.18.x
