### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by okcone** [choerodon/choerodon-front#9]
请问下是什么原因，react版本不符合么？还是漏了什么配置
![image](https://user-images.githubusercontent.com/22243114/96829418-35688d80-146c-11eb-9746-e8f4d2e53bee.png)

**Comment by sce9966** [comment]
同样问题，发现react的版本不一致导致的，我是将依赖删除重新安装解决的

**Comment by okcone** [comment]
> 同样问题，发现react的版本不一致导致的，我是将依赖删除重新安装解决的
重新安装的react版本是啥呢？

**Comment by okcone** [comment]
react版本选择的是多少呢？

**Comment by hqy1204** [comment]
@okcone front主模块的依赖版本是17.0.1。而子模块依赖版本是16.14.0

**Comment by sce9966** [comment]
@okcone 我主模块在package-lock.json 对react版本统一在 16.14.0，重新安装依赖解决的，希望能帮到你
